services:
  postgres:
    image: postgres:14.11-alpine3.19
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jafar
      - POSTGRES_PASSWORD=jafar456*-
      - POSTGRES_DB=facetrack
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
