services:
  postgres:
    image: postgres:14.11-alpine3.19
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jafar
      - POSTGRES_PASSWORD=jafar456*-
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: fallinnadim/facetrack:0.0.1-SNAPSHOT
    pull_policy: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  postgres_data: